#pragma once
#include <iostream>
#include <Vector>
#include "LeetCodeLibrary.h"
#include "string"
void TwoSumTest(LeetCodeLibrary);
void AddTwoNumbersTest(LeetCodeLibrary);
void findMedianSortedArraysTest(LeetCodeLibrary);
void longestPalindromeTest(LeetCodeLibrary);
void ConvertTest(LeetCodeLibrary);
void ReverseTest(LeetCodeLibrary);
void AtoiTest(LeetCodeLibrary);
void ThreeSumTest(LeetCodeLibrary);
void ThreeSumClosestTest(LeetCodeLibrary);
void LetterCombinationsTest(LeetCodeLibrary);