#pragma once
#include <iostream>
#include <Vector>
#include "LeetCodeLibrary.h"
#include "string"
void TwoSumTest(LeetCodeLibrary);
void AddTwoNumbersTest(LeetCodeLibrary);
void findMedianSortedArraysTest(LeetCodeLibrary);
void longestPalindromeTest(LeetCodeLibrary);